### ISSUE TITLE
Are there are privacy issues?

### ISSUE THREAD

**Issue by wenlzhang** [joelseq/obsidian-linkstowr#4]
Thank you for developing this plugin! My workflow with Obsidian misses a plugin like this for storing bookmarks.

I see that one needs to create an access token to use this plugin. Therefore, I am wondering how the bookmarks would be processed on the remote server. How is the privacy of users protected?

Is it possible to make this plugin work locally without sending users' bookmarks to remote servers?

**Comment by joelseq** [comment]
Hi! 

> I see that one needs to create an access token to use this plugin. Therefore, I am wondering how the bookmarks would be processed on the remote server. How is the privacy of users protected?

The API for this is open source as well (https://github.com/joelseq/linkshelf-api) in case you would like to take a look at it. The access token is following the [Seam-style prefixed api key](https://github.com/seamapi/prefixed-api-key) and that repo has more information about the benefits of it. I think the main point of interest for this discussion is "they have a hashed component so the server doesn't need to store the api key (reducing attack surface)". When the token is generated, the database only stores a hash of the long token before sending the full token to the user. This means that only the user should know the full token. Users can create an account with just a username and password so they don't need to share any personal information like email. The access token is just needed to associate links to a particular account but the links are **only stored in the database until it syncs to your local Obsidian vault**. Once the links sync to your vault successfully (using your access token), the links are deleted from the database so it's mainly meant to be like a temporary buffer to hold on to your links till it can sync to your vault.

> Is it possible to make this plugin work locally without sending users' bookmarks to remote servers?

All the components of this are open source ([Chrome extension](https://github.com/joelseq/linkshelf-extension), [Web app](https://github.com/joelseq/linkshelf-web), [Server](https://github.com/joelseq/linkshelf-api)) so it should be possible to self-host this either locally or on your own servers!

**Comment by wenlzhang** [comment]
Thank you for the clarification!

> All the components of this are open source ([Chrome extension](https://github.com/joelseq/linkshelf-extension), [Web app](https://github.com/joelseq/linkshelf-web), [Server](https://github.com/joelseq/linkshelf-api)) so it should be possible to self-host this either locally or on your own servers!

It would be great if there can be some tutorials for self-hosting it in the future.

**Comment by mAAdhaTTah** [comment]
@joelseq I'm interested in self-hosting but I _think_ the [API URL is hard-coded on plugin build](https://github.com/joelseq/obsidian-linkstowr/blob/main/src/utils/api.ts#L21C33-L21C33). Maybe this should be a setting? Edit: Chrome Extension probably needs a setting too?

**Comment by joelseq** [comment]
@mAAdhaTTah yeah I think making it an optional setting like "Custom server url" on both the Chrome extension as well as the Obsidian plugin would be a good idea! I'll try to spend some time on it this weekend and maybe write up a bit of a doc on self hosting as well.

**Comment by joelseq** [comment]
@wenlzhang, @mAAdhaTTah I just released a new version of the Obsidian plugin and Chrome extension which adds a setting for a custom server URL. The Chrome extension might take another day to get published due to the review. Sorry for the delay on this! I wanted to migrate the API + DB to use the latest version of SurrealDB (which made some underlying data model changes from the beta version) before adding support for self-hosting.

I'll try to work on some docs for self-hosting soon but if you'd like to get a head start, the main things would be:
- Create a deployment of SurrealDB [[docs](https://surrealdb.com/docs/deployment)]
- Create a deployment of the API with some env vars set. The API repo already has a fly.toml file which should make it easy to deploy to fly.io. The env vars needed are:
  - APP_DATABASE__HOST - this should point to the url where you deployed SurrealDB.
  - APP_DATABASE__USERNAME - the root user that you set for SurrealDB.
  - APP_DATABASE__PASSWORD - the password for the root user.
  - APP_DATABASE__PORT - should be `80`.
  - APP_DATABASE__NS - the namespace to use (e.g. prod).
  - APP_DATABASE__DB - the surrealdb "database" name (e.g. linkstowr).
  - JWT_ENCODING_SECRET - secret used for encoding the JWT used for the signup/signin.
  - HYPERDX_API_KEY - LinkStowr uses HyperDX for telemetry. The current API code I _think_ fails without this being set but I'll work on making this an optional component. I think providing some fake value here will at least cause a soft failure and not a hard crash.
  - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT - similar to above, will work on making this optional in the long term but I think passing in a fake value here should not make it hard crash.
  - OTEL_EXPORTER_OTLP_TRACES_PROTOCOL - similar to above.

**Comment by mAAdhaTTah** [comment]
@joelseq Thank you! I'll take a look at it soon. How are you hosting/deploying the front-end?

**Comment by joelseq** [comment]
I'm using Vercel for that but if you are mainly self hosting for yourself you could probably just run the web app locally with a `.env` file (like [this](https://github.com/joelseq/linkstowr-web/blob/main/.env.example)) and change that API URL to point to your custom server. Once you get a token you should be able to just use the Chrome extension and Obsidian plugin with that!

Alternatively, you can an also send a couple of curl requests to get a token like:

```
curl -X POST https://${yourserver}/signup \
   -H 'Content-Type: application/json' \
   -d '{"username": "username", "password":"password", "password_confirm": "password" }'
```

That will give you a JWT in the "token" field of the response. You can then use that to generate a token like this:

```
curl -X POST https://${yourserver}/api/tokens \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer ${token}' \
  -d '{"name": "my token"}'
```

**Comment by mAAdhaTTah** [comment]
@joelseq Is the Docker image published?

**Comment by joelseq** [comment]
@mAAdhaTTah sorry I haven't published it :(. The API repo does have a Dockerfile though

**Comment by mAAdhaTTah** [comment]
@joelseq Is that something you're planning on doing and/or would accept a PR implementing?

Semi-relatedly, why SurrealDB?

**Comment by joelseq** [comment]
@mAAdhaTTah I wasn't planning on doing it but I'd be happy to accept a PR! re: why SurrealDB, it seemed like a cool and interesting project so I thought that this might be a good opportunity to try it out. I especially liked that it was in Rust and can be run in embedded mode. Definitely regretting my choice a bit though now because the level of support for it is not great and there are a few weird bugs and issues :sweat_smile:

**Comment by mAAdhaTTah** [comment]
@joelseq Cool, I opened a PR here: https://github.com/joelseq/linkstowr-api/pull/11

RE SurrealDB: I had a feeling, as a fellow dev, that this was an "oh that looks neat, let me play with it" scenario lol. If you decide to move away from it, I'd also be interested in pitching in there, as I don't have a lot of Rust experience and it would be a similar "good opportunity to try it out" situation for me.

**Comment by joelseq** [comment]
Thanks for the PR! :pray:

> If you decide to move away from it, I'd also be interested in pitching in there, as I don't have a lot of Rust experience and it would be a similar "good opportunity to try it out" situation for me.

I don't have any plans yet for migrating away from SurrealDB as I just spent a lot of effort to update SurrealDB to the latest version and create the test suite for it :sweat_smile:. I think maybe if there are more issues that come up then I'll consider it more seriously and let you know!

**Comment by mAAdhaTTah** [comment]
@joelseq Fair! It's def a cool project.
