### ISSUE TITLE
Add support for `bookmarked_at` or similar

### ISSUE THREAD

**Issue by mAAdhaTTah** [joelseq/obsidian-linkstowr#5]
I'd like to capture the time the bookmark occurred at as part of my notes. Would be nice to have this added as a variable to the template. I think this also needs to be added to the API to work. If you have any suggestions/direction here, I could look at contributing this myself.

**Comment by joelseq** [comment]
That's a great idea! I see you already have a PR for this, thanks for creating it! I'll take a look at that a bit later today

**Comment by mAAdhaTTah** [comment]
@joelseq Yeah, we can discuss the implementation on the API side because I definitely have questions about that. On the Obsidian side, it currently "works" because you're doing a find/replace via regex based on the response payload, but there are two issues:

1. The value is saved and thus returned in UTC so it appears in the note in UTC rather than the user's time zone.
2. There are no formatting options available so you just get the raw string from the API output into the note.

I feel like there has to be something built-in here we can take advantage of to do this, right?

**Comment by joelseq** [comment]
@mAAdhaTTah For the API side I think it makes sense to store the date in UTC. For the Obsidian plugin side, since the plugin integrates with templater it's possible to use the momentjs object which templater exposes to format the string. I was able to get it to work by adding a property field to my personal template file like this:

```
bookmarked_at: <% moment('{{bookmarked_at}}').format('YYYY MM DD') %>
```

I just saved a link to test it out with your recent API change merged in and I managed to get a link file with the bookmark!

![image](https://github.com/joelseq/obsidian-linkstowr/assets/12389411/ee610d78-3dc9-44b0-a905-28d3ff6646e5)

The format can be tweaked to everything that [momentjs](https://momentjs.com/docs/#/displaying/) supports

**Comment by mAAdhaTTah** [comment]
Only issue is if someone doesn't use Templater (I landed on Quickadd for reasons I can't remember). It looks like you have [some logic for inserting & formatting dates already](https://github.com/joelseq/obsidian-linkstowr/blob/main/src/utils/template.ts#L47-L63) (although it isn't documented, I don't think) so maybe we can reuse that here. This would also enable us to add templating for the file title as well.

**Comment by joelseq** [comment]
Ah I see, yeah if Templater isn't being used it would be a bit more challenging. One way this can be handled could be to expose a setting for how to format date strings which can then be used to pre-format the bookmarked_at before it gets inserted into the template. What do you think about that?

**Comment by mAAdhaTTah** [comment]
@joelseq Main downside to that is you can't use different formats for different places, e.g. say you just want a date on the title but full date & time in the frontmatter. The plus side is it's way less complicated to maintain.

If you don't want to support file name templates, then you're unlikely to need multiple formats, so we could go with that, but if you do, I kinda think the extra flexibility is worth it.

Either way, I can implement whichever you'd prefer.

**Comment by mAAdhaTTah** [comment]
One other thought: more generally, I'm trying to consolidate a few services, and Linkstowr+Obsidian works well as a replacement for Pinboard. The last missing feature here is tags, which would complicate the templates quite a bit if we want to implement that. Not necessarily a requirement (adding tags to the notes after they sync is a valid approach), but something to consider.

**Comment by joelseq** [comment]
@mAAdhaTTah sorry for the delay in getting back to you on this, I had a really busy week :(. Yeah I agree I think the extra flexibility would be nice. I think your current PR mostly LGTM but left a couple of comments on it. 

> One other thought: more generally, I'm trying to consolidate a few services, and Linkstowr+Obsidian works well as a replacement for Pinboard. The last missing feature here is tags, which would complicate the templates quite a bit if we want to implement that. Not necessarily a requirement (adding tags to the notes after they sync is a valid approach), but something to consider.

Can you elaborate a bit more on what you were thinking for tags? Is this specifically to have tags in the front matter? I actually was thinking about tags from the start but kinda ended up not doing it because I thought they might not provide as much value on top of just being able to add tags within the note itself. Skeleton (the UI library the extension uses) has a [really nice component](https://www.skeleton.dev/components/input-chips) as well for entering tags which I was thinking could be useful.

**Comment by mAAdhaTTah** [comment]
> Can you elaborate a bit more on what you were thinking for tags? Is this specifically to have tags in the front matter?

Ostensibly, there's two pieces: 1. Adding tags at the point you bookmark it and 2. outputting those tags into the file. For the former, you'd need to update the Chrome extension and API to accept those tags, and the latter, the Obsidian plugin to output them. For the plugin, this where a more full-fledged templating process would be necessary, cuz t doesn't _need_ to be in frontmatter, (e.g outputting `#javascript` & `#programming` in the body of the note is a valid approach) so you'd need a way of looping over the list and rendering accordingly.

> I thought they might not provide as much value on top of just being able to add tags within the note itself. 

Yeah, honestly, that makes sense. The main advantage to having that built-in earlier in the process would be the ability to provide tags at the time you're adding the bookmark, which might be a better UX because you're looking at the page and can thus consider tags at that moment, but I'm not strongly tied to it.

The reason I bring this up tho is tied to the date format. If we're going to move ahead with adding tags, and thus need some more complicated templating anyway, I don't think it would make sense to define the date format as a setting because the template logic could handle that. If we don't want to add tags (and are thus looking at the ecosystem being "feature complete" at this point), then a setting might be fine.

**Comment by joelseq** [comment]
That makes sense! I don't think it would hurt to add tags as an additional feature especially if it can be valuable for creating tags for dates. Would you like to create a new task to track that so that we can close this one out? I'm not going to have time to work on it this month but can probably spend some time next month!

**Comment by mAAdhaTTah** [comment]
Will do! I may have some time to poke at this over the holidays as well.
